source ~/pyenv/bin/activate

DATASET_SIZE=100

FIXED="fixed"
SENTENCE="sentence"
SEMANTIC="semantic"

DENSE_RETRIEVAL="dense"
BM25_RETRIEVAL="bm25"
HYBRID_RETRIEVAL="hybrid"

RE_RANKING=1
TOP_K=20

k=5

python3 rag.py $DATASET_SIZE $FIXED $HYBRID_RETRIEVAL $k $RE_RANKING $TOP_K
